# Generated by Django 2.2 on 2019-04-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('field', models.URLField()),
                ('account', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('info', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
