# Generated by Django 2.2 on 2019-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20190417_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='info',
            field=models.TextField(),
        ),
    ]
